from __future__ import annotations

from typing import Protocol

from .models import AuditEvent, Member, QuarantineItem, Tenant


class AdminService(Protocol):
    def list_tenants(self) -> list[Tenant]: ...

    def get_tenant(self, id: str) -> Tenant: ...

    def list_members(self, tenant_id: str) -> list[Member]: ...

    def suspend_tenant(self, id: str, actor: str) -> Tenant: ...

    def list_jobs(self) -> list[dict]: ...

    def list_quarantine(self) -> list[QuarantineItem]: ...

    def add_quarantine(self, item: QuarantineItem) -> QuarantineItem: ...

    def list_audit(self) -> list[AuditEvent]: ...

    def append_audit(self, event: AuditEvent) -> None: ...

    def audit_csv(self) -> str: ...
